---
- name: make a build dir
  file: state=directory name=/root/bind-dockerized

- name: put Dockerfile
  template: src=Dockerfile dest=/root/bind-dockerized/Dockerfile

- name: put start.sh
  template: src=start.sh dest=/root/bind-dockerized/start.sh mode=0755

- name: build a Docker image for bind
  command: docker build -t gitinsky/bind:0.1.1 --rm /root/bind-dockerized

- name: tag it as latest
  command: docker build -t gitinsky/bind:latest --rm /root/bind-dockerized
